---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: {{ item.taskrun_with_flavor_name }}
spec:
  serviceAccountName: {{ sa_name }}
  taskRef:
    kind: Task
    name: {{ task_name }}
  params:
    - name: waitForSuccess
      value: 'true'
    - name: manifest
      value: |
        apiVersion: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        metadata:
          generateName: example-dv-
        spec:
          pvc:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
            volumeMode: Filesystem
          source:
            blank: {}
