apiVersion: v1
kind: Secret
metadata:
  name: {{ item.name }}
type: Opaque
stringData:
  password: mysecretpassword
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: {{ item.name }}
spec:
  taskRef:
    kind: Task
    name: {{ task_name }}
  params:
    - name: pvc
      value: example-pvc
    - name: sysprepCommands
      value: |
        update
        install make,ansible
        operations firewall-rules,defaults
        root-password file:/data/password
  workspaces:
    - name: data
      secret:
        name: {{ item.name }}
