apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows2k22-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: INSERT_WINDOWS_ISO_URL
    - name: preferenceName
      value: "windows.2k22"
    - name: autounattendConfigMapName
      value: windows2k22-autounattend
    - name: baseDvName
      value: win2k22
    - name: isoDVName
      value: win2k22
  pipelineRef:
    name: windows-efi-installer
  timeout: 1h0m0s
  serviceAccountName: pipeline      
