---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: server-deployer-run-
spec:
  pipelineRef:
    name: server-deployer
  taskRunSpecs:
    - pipelineTaskName: modify-data-object
      taskServiceAccountName: modify-data-object-task
    - pipelineTaskName: generate-ssh-keys
      taskServiceAccountName: generate-ssh-keys-task
    - pipelineTaskName: create-vm-from-manifest
      taskServiceAccountName: create-vm-from-manifest-task
    - pipelineTaskName: execute-in-vm
      taskServiceAccountName: execute-in-vm-task
