---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.43.0"
    tekton.dev/categories: Automation
    tekton.dev/tags: kubevirt
    tekton.dev/displayName: "{{ display_name_provider }} {{ nice_name }}"
    tekton.dev/platforms: "linux/amd64,linux/arm64,linux/s390x"
    artifacthub.io/maintainers: |
      - name: {{ maintainer_name }}
        email: {{ maintainer_email }}
    artifacthub.io/provider: {{ provider }}
    artifacthub.io/recommendations: |
      - url: {{ recommendation_url }}
    artifacthub.io/category: integration-delivery
  labels:
    app.kubernetes.io/version: {{ catalog_version }}
  name: {{ task_name }}
spec:
  description: >-
    Run virt-customize command on given PVC. Usefull for manipulation with virtual machine's disks.
  params:
    - name: pvc
      description: PersistentVolumeClaim to run the the virt-customize script in. PVC should be in the same namespace as taskrun/pipelinerun.
      type: string
    - name: virtCommands
      description: virt-customize commands in "--commands-from-file" format.
      type: string
      default: ""
    - name: verbose
      description: Enable verbose mode and tracing of libguestfs API calls.
      type: string
      default: 'false'
    - name: additionalVirtOptions
      description: Additional options to pass to virt-customize.
      type: string
      default: ""
  steps:
    - name: run-virt-customize
      image: "{{ main_image }}:{{ version }}"
      command:
        - entrypoint
      args:
        - '--verbose'
        - $(params.verbose)
      env:
        - name: COMMAND
          value: disk-virt-customize
        - name: VIRT_COMMANDS
          value: $(params.virtCommands)
        - name: ADDITIONAL_VIRT_OPTIONS
          value: $(params.additionalVirtOptions)
        - name: LIBGUESTFS_BACKEND
          value: direct
      computeResources:
        limits:
          devices.kubevirt.io/kvm: '1'
          devices.kubevirt.io/tun: '1'
          devices.kubevirt.io/vhost-net: '1'
        requests:
          devices.kubevirt.io/kvm: '1'
          devices.kubevirt.io/tun: '1'
          devices.kubevirt.io/vhost-net: '1'
      volumeMounts:
        - mountPath: /mnt/appliance/
          name: guestfsappliance
        - mountPath: /mnt/targetpvc/
          name: targetpvc
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - "ALL"
  volumes:
    - name: guestfsappliance
      emptyDir: {}
    - name: targetpvc
      persistentVolumeClaim:
        claimName: $(params.pvc)
  workspaces:
    - name: data01
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data01
    - name: data02
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data02
    - name: data03
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data03
    - name: data04
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data04
    - name: data05
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data05
    - name: data06
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data06
    - name: data07
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data07
    - name: data08
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data08
    - name: data09
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data09
    - name: data10
      description: |
        An optional workspace that may contain files or secrets to be
        used during the virt-customize run.
      optional: true
      mountPath: /data10
