---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-datavolume-task
rules:
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - cdi.kubevirt.io
    resources:
      - datavolumes

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-datavolume-task

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-datavolume-task
roleRef:
  kind: ClusterRole
  name: create-datavolume-task
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: create-datavolume-task
    namespace: TARGET_NAMESPACE
