---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ item.role_type }}
metadata:
  name: {{ role_name }}
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
    apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachineinstances
  - verbs:
      - 'update'
    apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachines/start
  - verbs:
      - update

    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims

