---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: {{ item.taskrun_with_flavor_name }}
spec:
  serviceAccountName: {{ sa_name }}
  taskRef:
    kind: Task
    name: {{ task_name }}
  params:
  - name: templateName
    value: vm-template-example
  - name: memory
    value: "2G"
