FROM fedora:30

ENV REPO_DIR=/go/src/github.com/kubevirt/kubevirt-tekton-tasks/

RUN mkdir -p ${REPO_DIR}
RUN chmod 777 ${REPO_DIR}
ADD . ${REPO_DIR}
WORKDIR ${REPO_DIR}

RUN dnf install -y jq ansible make && rm -rf /var/cache/yum /var/cache/dnf
RUN chmod uga+w /etc/passwd

#set permissions for ansible tmp folder
RUN mkdir -p /.ansible/tmp
RUN chmod -R 777 /.ansible
