#!/usr/bin/env bash

export DEV_MODE="${DEV_MODE:-false}"
export STORAGE_CLASS="${STORAGE_CLASS:-}"
export NUM_NODES=${NUM_NODES:-2}
export DOWNLOAD_CONFIGMAPS="${DOWNLOAD_CONFIGMAPS:-false}"
export IMAGE_DESTINATION="${IMAGE_DESTINATION:-}"
export REGISTRY_ACCESS_KEY_ID="${REGISTRY_ACCESS_KEY_ID:-}"
export REGISTRY_SECRET_KEY="${REGISTRY_SECRET_KEY:-}"
