---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    task.kubevirt.io/associatedServiceAccount: {{ sa_name }}
  labels:
    task.kubevirt.io/type: {{ task_name }}
    task.kubevirt.io/category: {{ task_name }}
  name: {{ task_name }}
spec:
  params:
    - description: Name of a VM to execute the action in
      name: vmName
      type: string
    - description: Namespace of a VM to execute the action in (defaults to active namespace)
      name: vmNamespace
      type: string
      default: ""
    - description: Secret to use when connecting to a VM
      name: secretName
      type: string
    - description: Command to execute in a VM
      name: command
      type: array
      default: []
    - description: Arguments of a command
      name: args
      type: array
      default: []
    - description: Script to execute in a VM
      name: script
      type: string
      default: ""
  steps:
    - name: execute-in-vm
      image: {{ main_image }}
      command:
        - execute-in-vm
        - '--vm-name'
        - $(params.vmName)
        - '--vm-namespace'
        - $(params.vmNamespace)
        - '--command'
        - $(params.command)
        - '--command-args'
        - $(params.args)
        - '--script'
        - $(params.script)
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - mountPath: /data/vmcredentials/
          name: vmcredentials
  volumes:
    - name: vmcredentials
      secret:
        secretName: $(params.secretName)
