---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows10-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: ${WIN_IMAGE_DOWNLOAD_URL}
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: {{ pipelines_catalog }}
      - name: type
        value: {{ catalog_type }}
      - name: kind
        value: pipeline
      - name: name
        value: {{ item.pipeline_name }}
      - name: version
        value: {{ catalog_version }}
