---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ item.role_type }}
metadata:
  name: {{ role_name }}
rules:
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - cdi.kubevirt.io
    resources:
      - datavolumes
