
- name: "Prepare {{ item.role_id }} role directory"
  file:
    path: "{{ role_output_dir }}"
    state: directory
- name: Generate role
  template:
    src: "{{ manifest_templates_dir }}/{{ task_name }}-role.yaml"
    dest: "{{ role_output_dir }}/00-{{ task_name }}-role.yaml"
    mode: "{{ default_file_mode }}"
- name: Generate service account
  template:
    src: "{{ manifest_templates_dir }}/{{ task_name }}-sa.yaml"
    dest: "{{ role_output_dir }}/01-{{ task_name }}-sa.yaml"
    mode: "{{ default_file_mode }}"
- name: Generate role binding
  template:
    src: "{{ manifest_templates_dir }}/{{ task_name }}-role-binding.yaml"
    dest: "{{ role_output_dir }}/02-{{ task_name }}-role-binding.yaml"
    mode: "{{ default_file_mode }}"
- name: Make rbac bundle
  assemble:
    src: "{{ role_output_dir }}"
    dest: "{{ role_output_dir }}/{{ task_name }}-{{ item.role_id }}-rbac.yaml"
    mode: "{{ default_file_mode }}"
    delimiter: '\n'
